### PR TITLE
Add monitoring endpoints for website, app-pool, and webserver

### PR DESCRIPTION
**Pull request by jimmyca15**
# Microsoft.IIS.Administration.WebServer.Monitoring

This plugin provides data to measure performance and health of the webserver. The data is scoped to the webserver as a whole, application pools, and web sites.

### Web Server
_/api/webserver/monitoring/{id}_
```
{
    "id": "{id}",
    "network": {
        "bytes_sent_sec": "47",
        "bytes_recv_sec": "111",
        "connection_attempts_sec": "0",
        "total_connection_attempts": "8",
        "current_connections": "0"
    },
    "requests": {
        "active": "0",
        "per_sec": "0",
        "total": "87"
    },
    "memory": {
        "private_working_set": "25858048",
        "working_set": "54882304",
        "private_bytes": "97120256",
        "available": "337850368"
    },
    "cpu": {
        "percent_usage": "0",
        "threads": "58",
        "processes": "1"
    },
    "disk": {
        "io_write_operations_sec": "5",
        "io_read_operations_sec": "5",
        "page_faults_sec": "5"
    },
    "cache": {
        "file_cache_count": "1",
        "file_cache_memory_usage": "689",
        "file_cache_hits": "39",
        "file_cache_misses": "213",
        "total_files_cached": "5",
        "output_cache_count": "0",
        "output_cache_memory_usage": "0",
        "output_cache_hits": "0",
        "output_cache_misses": "138",
        "uri_cache_count": "2",
        "uri_cache_hits": "116",
        "uri_cache_misses": "22",
        "total_uris_cached": "11"
    },
    "_links": {
        "self": {
            "href": "/api/webserver/monitoring/{id}"
        }
    }
}
```

### Application Pool
_/api/webserver/application-pools/monitoring/{id}_
```
{
    "id": "{id}",
    "requests": {
        "active": "0",
        "per_sec": "0",
        "total": "66"
    },
    "memory": {
        "private_working_set": "25862144",
        "working_set": "54886400",
        "private_bytes": "96890880"
    },
    "cpu": {
        "percent_usage": "0",
        "threads": "47",
        "processes": "1"
    },
    "disk": {
        "io_write_operations_sec": "5",
        "io_read_operations_sec": "5",
        "page_faults_sec": "1"
    },
    "cache": {
        "file_cache_count": "1",
        "file_cache_memory_usage": "689",
        "file_cache_hits": "39",
        "file_cache_misses": "213",
        "total_files_cached": "5",
        "output_cache_count": "0",
        "output_cache_memory_usage": "0",
        "output_cache_hits": "0",
        "output_cache_misses": "138",
        "uri_cache_count": "0",
        "uri_cache_hits": "116",
        "uri_cache_misses": "22",
        "total_uris_cached": "11"
    },
    "application_pool": {
        "name": "DefaultAppPool",
        "id": "{id}",
        "status": "started",
        "_links": {
            "self": {
                "href": "/api/webserver/application-pools/{id}"
            }
        }
    },
    "_links": {
        "self": {
            "href": "/api/webserver/application-pools/monitoring/{id}"
        }
    }
```

### Web Site
_/api/webserver/websites/monitoring/{id}_
```
{
    "id": "{id}",
    "uptime": "2179",
    "network": {
        "bytes_sent_sec": "0",
        "bytes_recv_sec": "0",
        "connection_attempts_sec": "0",
        "total_connection_attempts": "8",
        "current_connections": "0"
    },
    "requests": {
        "per_sec": "0",
        "total": "87"
    },
    "website": {
        "name": "Default Web Site",
        "id": "dhiL0OtbyDek158oOB7FtQ",
        "status": "started",
        "_links": {
            "self": {
                "href": "/api/webserver/websites/{id}"
            }
        }
    },
    "_links": {
        "self": {
            "href": "/api/webserver/websites/monitoring/{id}"
        }
    }
}
```

### CODE REVIEW

**Comment by jimmyca15** [comment]
We have decided to integrate application pool fields into the web site to make monitoring web sites a simpler task. One side effect of this approach is that the performance data that comes from the application pool is only accurate at the web site level if the web site is the only site in the application pool. If multiple sites are in the same application pool, these values will be the same for each web site.

**Comment by shirhatti** [comment]
> We have decided to integrate application pool fields into the web site to make monitoring web sites a simpler task

Can you show what the updated */api/webserver/websites/monitoring/{id}* endpoint looks like?

**Comment by jimmyca15** [comment]
Tests have now been added.

**Comment by jimmyca15** [comment]
I didn't add this in but in the future it will be good to have remaining disk space. The System.IO.DriveInfo APIs can give us this info and we can fit it in to the webserver resource.

**Pull request merged**
