### PR TITLE
Upgrade to .net core 3.1

### PR DESCRIPTION
**Pull request by refaelyehuda**
As I requested in #301. 

Can you please upgrade the package to .Net Core 3.1.

I updated the TargetFramework in csproj file of all projects.

The tests passed successfully.

Please let me know if you need to do more things to upgrade this package to .Net Core 3.1

Thanks

### CODE REVIEW

**Comment by shirhatti** [comment]
The dependency authoring in the installer needs to be updated as well- https://github.com/microsoft/IIS.Administration/blob/dev/installer/IISAdministrationBundle/iisadministration.wxs#L32-L85

**Comment by refaelyehuda** [comment]
The dependency authoring in the installer updated as well.

Please let me know if you need to do more things to upgrade this package to .Net Core 3.1.

Thanks

**Comment by shirhatti** [comment]
Still uses ASP.NET Core 2.1. See this package refs- https://github.com/microsoft/IIS.Administration/blob/dev/build/version.props#L10-L14

To upgrade to ASP.NET Core 3.1, you'll need to stop using package refs and switch to using a framework reference
`<FrameworkReference Include="Microsoft.AspNetCore.App" />`

I suspect there might be a  few breaking API changes in ASP.NET Core which will make more than just a mechanical version number update

**Comment by yaqiyang** [comment]
I am migrating it to .Net 6.0. No need to keep this PR

**Pull request closed without merging**
